export const MOTION = {
  easeOut: [0.16, 1, 0.3, 1] as const,
  easeInOut: [0.87, 0, 0.13, 1] as const,
  easeSpring: [0.34, 1.56, 0.64, 1] as const,
  fast: 0.25,
  mid: 0.6,
  slow: 1.2,
  loader: 0.6,
  cameraLerp: 0.05,
  mouseLerp: 0.08,
  colorLerp: 0.03,
  scrollScrub: 0.35,
  scrollHeight: 620,
  charStagger: 0.04,
  lineStagger: 0.18,
  panelStagger: 0.12,
  dragonHeadStiffness: 0.1,
  dragonDamping: 0.8,
  dragonSegments: 30,
  dragonSegmentLength: 16,
  particleReturnSpring: 0.07,
  particleDamping: 0.86,
  particleInfluenceRadius: 100,
  particlePushStrength: 180,
  particleSampleStep: 3,
  particleMaxCount: 12000,
  dragonProgressStart: 0.55,
  dragonProgressEnd: 0.7,
  dragonFadeSeconds: 0.8,
  bloomIntensityBase: 0.45,
  bloomIntensityScale: 0.3,
  bloomThreshold: 0.85,
  bloomSmoothing: 0.2,
  dofFocusDistance: 0.02,
  dofFocalLength: 0.015,
  dofBokehScale: 1.4,
  vignetteOffset: 0.3,
  vignetteDarkness: 0.52,
  mouseInfluenceX: 2,
  mouseInfluenceY: 1.2,
  cameraFovDefault: 60,
  cameraNear: 0.1,
  cameraFar: 200,
} as const;

export const EASINGS = {
  out: `cubic-bezier(${MOTION.easeOut.join(',')})`,
  inOut: `cubic-bezier(${MOTION.easeInOut.join(',')})`,
  spring: `cubic-bezier(${MOTION.easeSpring.join(',')})`,
} as const;
