// lib/data.ts — All portfolio content. Edit this file to customize.

export const personal = {
  name: 'Your Name',
  initials: 'YN',
  tagline: 'Full Stack Engineer · AI Specialist',
  headline: 'I build things\nthat matter.',
  subline: 'Crafting high-performance applications at the intersection of engineering and intelligence.',
  email: 'hello@yourname.dev',
  location: 'San Francisco, CA',
  available: true,
  availabilityText: 'Available for freelance & full-time',
  social: {
    github: 'https://github.com/yourusername',
    linkedin: 'https://linkedin.com/in/yourusername',
    twitter: 'https://twitter.com/yourusername',
    dribbble: 'https://dribbble.com/yourusername',
  },
}

export const timeline = [
  {
    id: 1,
    year: '2024',
    month: 'Mar',
    role: 'Senior AI Engineer',
    company: 'TechCorp AI',
    companyUrl: '#',
    summary: 'Leading development of LLM-powered features used by 2M+ users. Reduced inference latency by 60%.',
    tags: ['Python', 'LLMs', 'React', 'AWS'],
    color: '#4F8EF7',
  },
  {
    id: 2,
    year: '2022',
    month: 'Jun',
    role: 'Full Stack Lead',
    company: 'StartupXYZ',
    companyUrl: '#',
    summary: 'Scaled product from 0 to 150k users. Built real-time collaboration features and event-driven microservices.',
    tags: ['Next.js', 'Node.js', 'Postgres', 'Redis'],
    color: '#8B5CF6',
  },
  {
    id: 3,
    year: '2020',
    month: 'Jan',
    role: 'Software Engineer',
    company: 'Digital Agency',
    companyUrl: '#',
    summary: 'Developed client-facing dashboards and internal tooling for Fortune 500 clients.',
    tags: ['React', 'GraphQL', 'TypeScript'],
    color: '#06B6D4',
  },
  {
    id: 4,
    year: '2018',
    month: 'Sep',
    role: 'CS Graduate',
    company: 'University of Technology',
    companyUrl: '#',
    summary: 'B.Sc. Computer Science. Thesis on distributed systems and consensus algorithms.',
    tags: ['Algorithms', 'Distributed Systems', 'Research'],
    color: '#10B981',
  },
]

export const skillDomains = [
  {
    id: 'engineering',
    label: 'Engineering',
    color: '#4F8EF7',
    skills: [
      { name: 'React / Next.js', years: 6, proficiency: 95, tools: ['Redux', 'Zustand', 'RTK'] },
      { name: 'TypeScript', years: 5, proficiency: 90, tools: ['Zod', 'tRPC'] },
      { name: 'Node.js', years: 7, proficiency: 88, tools: ['Express', 'Fastify', 'NestJS'] },
      { name: 'Python', years: 5, proficiency: 85, tools: ['FastAPI', 'Django', 'Poetry'] },
      { name: 'PostgreSQL', years: 5, proficiency: 82, tools: ['Prisma', 'Drizzle'] },
      { name: 'GraphQL', years: 3, proficiency: 78, tools: ['Apollo', 'Hasura'] },
    ],
  },
  {
    id: 'ai',
    label: 'AI / ML',
    color: '#8B5CF6',
    skills: [
      { name: 'LLM Engineering', years: 3, proficiency: 90, tools: ['OpenAI', 'Anthropic', 'Langchain'] },
      { name: 'RAG Systems', years: 2, proficiency: 85, tools: ['Pinecone', 'Weaviate', 'pgvector'] },
      { name: 'PyTorch', years: 3, proficiency: 75, tools: ['Transformers', 'PEFT'] },
      { name: 'Data Engineering', years: 4, proficiency: 80, tools: ['Pandas', 'dbt', 'Airflow'] },
    ],
  },
  {
    id: 'design',
    label: 'Design / UX',
    color: '#06B6D4',
    skills: [
      { name: 'Three.js / WebGL', years: 3, proficiency: 82, tools: ['R3F', 'Drei', 'GLSL'] },
      { name: 'Framer Motion', years: 4, proficiency: 88, tools: ['GSAP', 'Lottie'] },
      { name: 'Figma', years: 4, proficiency: 80, tools: ['Prototyping', 'Design Systems'] },
      { name: 'CSS / Tailwind', years: 6, proficiency: 92, tools: ['CSS Modules', 'styled-components'] },
    ],
  },
  {
    id: 'leadership',
    label: 'Leadership',
    color: '#F59E0B',
    skills: [
      { name: 'Team Lead', years: 3, proficiency: 85, tools: ['Agile', 'Scrum', 'OKRs'] },
      { name: 'System Design', years: 5, proficiency: 88, tools: ['Architecture', 'Cloud', 'Scalability'] },
      { name: 'Code Review', years: 5, proficiency: 90, tools: ['GitHub', 'Linear'] },
      { name: 'Mentoring', years: 3, proficiency: 85, tools: ['1:1s', 'Documentation'] },
    ],
  },
]

export const projects = [
  {
    id: 1,
    tag: 'AI Platform',
    title: 'NeuralChat',
    summary: 'LLM-powered customer support platform handling 50k conversations/day with 95% resolution rate.',
    description: `A production-grade AI customer support system built with multi-modal LLMs, retrieval-augmented generation, and real-time streaming. Deployed at enterprise scale with zero-downtime deployments.`,
    problem: 'Enterprise teams were drowning in support tickets with slow response times and inconsistent quality.',
    solution: 'Built a RAG-powered LLM system that learns from previous resolutions, routes complex cases to humans, and provides instant accurate responses at scale.',
    results: ['60% reduction in response time', '95% automated resolution rate', '$2.4M annual cost savings', '99.9% uptime SLA'],
    stack: ['Next.js', 'Python', 'OpenAI', 'Pinecone', 'Postgres', 'Redis'],
    color: '#4F8EF7',
    accentBg: 'rgba(79, 142, 247, 0.05)',
    liveUrl: '#',
    githubUrl: '#',
    featured: true,
  },
  {
    id: 2,
    tag: 'Web App',
    title: 'FlowBoard',
    summary: 'Real-time collaborative project management tool with CRDT-based conflict resolution and live cursors.',
    description: `A Notion-meets-Linear collaborative workspace built on CRDTs for conflict-free real-time editing. Supports 100+ concurrent users per document with sub-100ms latency.`,
    problem: 'Teams collaborating across time zones faced merge conflicts and stale data issues in existing tools.',
    solution: 'Implemented Yjs CRDTs over WebSockets with operational transforms for seamless real-time collaboration.',
    results: ['100+ concurrent users per doc', '<50ms sync latency', '10k active teams', 'ProductHunt #1 of the day'],
    stack: ['React', 'Node.js', 'WebSockets', 'Yjs', 'MongoDB', 'Redis'],
    color: '#8B5CF6',
    accentBg: 'rgba(139, 92, 246, 0.05)',
    liveUrl: '#',
    githubUrl: '#',
    featured: true,
  },
  {
    id: 3,
    tag: 'Open Source',
    title: 'QueryForge',
    summary: 'Natural language to SQL with schema-aware LLM completions and auto-generated migrations.',
    description: `An open-source CLI and web UI that converts natural language queries into optimized SQL, with context-aware completions and auto-generated Prisma migrations.`,
    problem: 'Junior developers and non-technical stakeholders struggled to write efficient database queries.',
    solution: 'Fine-tuned an LLM on schema + query pairs with chain-of-thought reasoning for complex JOINs and aggregations.',
    results: ['2.3k GitHub stars', '150+ contributors', 'Featured in JavaScript Weekly', 'Used by 800+ companies'],
    stack: ['TypeScript', 'OpenAI', 'Prisma', 'CLI', 'PostgreSQL'],
    color: '#10B981',
    accentBg: 'rgba(16, 185, 129, 0.05)',
    liveUrl: '#',
    githubUrl: '#',
    featured: false,
  },
  {
    id: 4,
    tag: 'Mobile / Web',
    title: 'PulseMetrics',
    summary: 'Real-time analytics dashboard with ML-powered anomaly detection and automated incident reports.',
    description: `A unified analytics platform that aggregates metrics from 30+ data sources, applies ML anomaly detection, and automatically generates executive reports.`,
    problem: 'Engineering teams spent hours manually reviewing dashboards and writing incident post-mortems.',
    solution: 'Built an ML pipeline for automated anomaly detection with plain-English explanations and auto-generated runbooks.',
    results: ['30+ data source integrations', '3hr → 10min incident response', '98% anomaly detection accuracy', 'SOC2 compliant'],
    stack: ['React', 'Python', 'ClickHouse', 'Kafka', 'Kubernetes'],
    color: '#F59E0B',
    accentBg: 'rgba(245, 158, 11, 0.05)',
    liveUrl: '#',
    githubUrl: '#',
    featured: false,
  },
]

export const testimonials = [
  {
    id: 1,
    quote: 'Rarely do you encounter a developer who combines deep technical expertise with genuine product intuition. The architecture decisions made on our core platform still hold up two years later — that's a testament to how thoughtfully everything was designed.',
    name: 'Sarah Chen',
    role: 'VP Engineering',
    company: 'TechCorp AI',
    linkedIn: '#',
    featured: true,
  },
  {
    id: 2,
    quote: 'Shipped our entire real-time collaboration engine in 6 weeks, with quality that outpaced engineers I've worked with at FAANG companies. The code is exceptionally clean, well-documented, and a joy to build on top of.',
    name: 'Marcus Johnson',
    role: 'CTO',
    company: 'FlowBoard Inc.',
    linkedIn: '#',
    featured: false,
  },
  {
    id: 3,
    quote: 'The AI system built for our support team reduced our ticket backlog by 60% in the first month. More impressive than the results was how methodically the problem was approached — understanding the domain before touching code.',
    name: 'Priya Patel',
    role: 'Head of Product',
    company: 'NeuralBase',
    linkedIn: '#',
    featured: false,
  },
  {
    id: 4,
    quote: 'I've worked with many senior engineers, but the combination of speed, quality, and communication here was exceptional. Every standup was clear, blockers were surfaced early, and the final product exceeded our expectations.',
    name: 'David Kim',
    role: 'Founder & CEO',
    company: 'StartupXYZ',
    linkedIn: '#',
    featured: false,
  },
]
